name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  '14.x'
      - run:  git config --global user.email "jon.ldg85@gmail.com"
      - run:  git config --global user.name "Jon"
      - run: npm i
      - run: npm run deploy
